--------------------------------------------------------
--  Arquivo criado - terça-feira-abril-08-2025   
--------------------------------------------------------
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1PARCELA_FATUR_CTR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKFAIXA_APROV_AO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKITEM_SOBRA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTS_GRUPO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKFERIADO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_FINANCEIRO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKSERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE3HISTORICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKUSUARIO_CARGO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPRECO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPAIS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__CONTRATO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1NOTIFICA_DESLIGA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK2ORDEM_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1CONDICAO_PAGTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCT_TRANSICAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMI_METAS_RADIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1XML_LOG.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1JOB_RECEITA_CTR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2ORDEM_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TIPO_PRODUTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1APONTAM_HORA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE4PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKSETOR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKUSUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKNUMERO_OS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1FI_TIPO_IMPOSTO_PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKEMPR_FATUR_SIST_EXT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2ABATIMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMI_CARGA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE4ITEM_CRONO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE3ITEM_CRONO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKXML_LOG.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKEVENTO_CONFIG.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKORCAM_FLUXO_APROV.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKFI_TIPO_IMPOSTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPESSOA_NITEM_PDR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKITEM_DECUP.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO_OS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1REL_OS_TLINE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO_COMUNICADO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKREL_RENTAB_JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_DADO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1PONTO_INTEGRACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPARAMETRO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ARQUIVO_NF.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1NATUREZA_OPER_FATUR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKSTATUS_AUX_OPORT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKJOB_NITEM_PDR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1SETOR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1MI_METAS_DIGITAL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__CRONOGRAMA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKITEM_CRONO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1GRUPO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKITEM_CRONO_USU.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TIPO_OS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKREL_FLUXO_CHECKIN.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE3ITEM.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKSALARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TS_TRANSICAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1PARCELA_CONTRATO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTAREFA_LINK.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE4HISTORICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO_OPORTUNIDADE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1INTERACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKFREQUENCIA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1OS_USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKCENARIO_SERVICO_ITEM.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKREL_APON_MENS_VAL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1EMPRESA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1DIA_ALOCACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCARTA_FLUXO_APROV.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCRONOGRAMA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE8CARTA_ACORDO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_TP_ATRIBUTO_VALOR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ARQUIVO_CARTA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2COMENTARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2ITEM_SOBRA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1CONTRATO_HORAS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1DEVOL_REALIZ.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_LINK.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCONDICAO_PAGTO_DET.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1PRODUTO_FISCAL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMARK.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMI_DAYPART_VAR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE3MILESTONE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKITEM_CRONO_PRE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1NOTIFICA_USU_AVULSO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKGRUPO_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1OPORTUNIDADE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1MI_DAYPART.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKGRUPO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1RELACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTS_APROVADOR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMOD_ITEM_CRONO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE6PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2TASK.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKSA_EMP_RESP.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TIPO_OBJETO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1DOCUMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_JOB_MOD_CRONO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ARQUIVO_PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKAPONTAM_PROGR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_PRODUTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_APONTAM.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTAREFA_AFAZER.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKRELACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TIPO_DADO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKORCAM_NITEM_PDR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1ORDEM_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1PARCELA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE7PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKJOB_USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_APONTAM_JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_TRANSICAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1EVENTO_MOTIVO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMI_VERSAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKREL_APON_MENS_COL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKHISTORICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2ITEM_NOTA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_DOCUMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE7CARTA_ACORDO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKAPONTAM_DATA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__MV_NEGOCIACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKBRIEF_AREA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_MILESTONE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCONDICAO_PAGTO_DIA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKHIST_ENDER.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE3PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKAREA_DICION_VALOR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKFATURAMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2CARTA_ACORDO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKFAIXA_APROV_OS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCONTEXTO_CRONO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPAPEL_PRIV_TFIN.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__OS_ATRIBUTO_VALOR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1DICION_EMP_VAL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE5TASK.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPAPEL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCATEGORIA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKDICION_EMP.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMOD_CRONO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2CTX_ARQUIVO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPARCELA_FATUR_CTR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ARQUIVO_DOCUMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__PRODUTO_CLIENTE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE5ORDEM_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE5HISTORICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKINTERACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ITEM_FATUR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKITEM_ADIANT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMI_CRIT_SEC.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCONTRATO_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK2CENARIO_MOD_CONTR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCENARIO_SERVICO_HORAS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK2MODAL_CONTRATACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKNOTIFICA_FILA_USU.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_ARQUIVO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE5PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__OS_USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKERRO_LOG.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKVERSAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_PROD_TIPO_OS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKORDEM_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2APONTAM_HORA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCAMPANHA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKGRUPO_PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMI_METAS_PRINT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1AVAL_FORNEC.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMI_METAS_DIGITAL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKFATURAMENTO_CTR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_DOC_NF.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCARTA_ACORDO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ABATIMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1VOLUME.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TIPO_FINANCEIRO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE3NOTIFICA_FILA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__ARQUIVO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1MI_PI.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_HORAS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1BRIEF_HIST.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO_TASK.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1JOB_TIPO_PRODUTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1TAREFA_LINK.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKSISTEMA_EXTERNO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCENARIO_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTS_EQUIPE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1NOTA_FISCAL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKSIST_EXT_PONTO_INT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__GRUPO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKNOTA_FISCAL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1SIST_EXT_PARAMETRO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\IDX03_MV_TAREFA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKITEM.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKDEPARTAMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1PRODUTO_CLIENTE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1CONTRATO_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2CEP.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKUNIDADE_NEGOCIO_CLI.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKNOTIFICA_FILA_USU.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKUSUARIO_PAPEL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKFAIXA_APROV_PAPEL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKJOB_HORAS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__USUARIO_CARGO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2OS_EVENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1TASK_COMENT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKAPONTAM_DATA_EV.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2SOBRA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKLANCAMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKITEM_FATUR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMI_PI.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1OS_AFAZER.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_PECA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\IDX03_MV_ORDEM_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPREFERENCIA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPAPEL_PRIV_TPESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPADRAO_PLANILHA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTAREFA_USUARIO_DATA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ITEM_CRONO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1APONTAM_DATA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKTAREFA_TIPO_PRODUTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPAPEL_PRIV_TDOC.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPAPEL_PRIV_TJOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1CONTEXTO_CRONO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO_PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK2EMPRESA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO_TAREFA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTAB_FERIADO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO_ORCAMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1PARCELA_CARTA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1FERIADO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE4ITEM.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPAPEL_PRIV_AREA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1HIST_ENDER.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1CEP.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKAJUSTE_JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1CENARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKADIANT_DESP.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCENARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO_CARTA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKUNIDADE_NEGOCIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE3NOTA_FISCAL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPESSOA_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTASK_HIST_CIENCIA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2ITEM_CARTA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPARCELA_CONTRATO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_TIPO_PRODUTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKUSUARIO_COENDER.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKFI_BANCO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TAREFA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKNATUREZA_ITEM_INC.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCONTRATO_HORAS_USU.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCENARIO_SERVICO_USU.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKTIPO_TAREFA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKNOTIFICA_FILA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPARCELA_CARTA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPAPEL_PRIV_TOS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ADIANT_REALIZ.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTAREFA_TP_ATRIB_VALOR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKJOB_PECA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKNOTIFICA_USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPARCELA_NF.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKUSUARIO_ENDER.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1APONTAM_ENCE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1FI_TIPO_IMPOSTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TIPO_DOC_NF.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__OS_NEGOCIACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1EVENTO_CONFIG.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKEMPR_RESP_SIST_EXT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPIFIC_PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKLINK_DIRETO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKNOTIFICA_FILA_EMAIL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_ACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_FLUXO_APROV.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1NOTIFICA_FILA_USU.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKGRUPO_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1FI_BANCO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1AJUSTE_JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_OS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCONTRATO_SERV_VALOR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1TIPIFIC_PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMI_DAYPART.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\IDX06_MV_TAREFA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOPORT_USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1CLASSE_PRODUTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPRODUTO_CLIENTE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_CONTRATO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1PAPEL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPONTO_INTEGRACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO_CONTRATO_FISICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMI_CARGA_DESCARTE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_ATRIBUTO_VALOR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKQUADRO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2NOTIFICA_FILA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTAREFA_USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKEQUIPE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKITEM_CARTA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE4JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1ADIANT_DESP.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE3TAREFA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_JOB_USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__ORDEM_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1CRONOGRAMA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKDIA_ALOCACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2PARCELA_FATUR_CTR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKITEM_CRONO_DEST.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1MOD_CRONO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_NEGOCIACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKFAIXA_APROV.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__METADADO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ORCAMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKCT_TRANSICAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKFI_TIPO_IMPOSTO_FAIXA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKDOCUMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKTAXA_FINANC1.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__VOLUME.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKADNNET_IN.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1PRIVILEGIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMILESTONE_USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO_CONTRATO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TIPO_PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1DESP_REALIZ.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKDEVOL_REALIZ.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKAVAL_FORNEC.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKBRIEFING.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1STATUS_AUX_OPORT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE4NOTIFICA_FILA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TIPO_ACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO_JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMODAL_CONTRATACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ITEM_DECUP.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOPORT_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__TIPO_OS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ITEM.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_PRODUTO_PRECO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2REL_OS_TLINE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2PARCELA_CONTRATO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKSERVIDOR_ARQUIVO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1NATUREZA_ITEM.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCENARIO_SERVICO_ITEM.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKNOTIFICA_FILA_EMAIL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKQUADRO_COLUNA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKDICIONARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\IDX02_MV_ORDEM_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1MI_METAS_RADIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKSOBRA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1OS_TIPO_PRODUTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPESQUISA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE4APONTAM_HORA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TIPO_ARQUIVO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1OS_HORAS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE3JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKCENARIO_SERVICO_USU.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKAPONTAM_ENCE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1NOTIFICA_CONFIG.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1UNIDADE_NEGOCIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKBRIEF_DICION_VALOR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1CAMPANHA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1MI_METAS_OOH.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2ARQUIVO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKUSUARIO_EMPRESA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1OS_EVENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKITEM_NOTA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1EVENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKDUPLICATA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKQUADRO_EQUIPE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2NOTA_FISCAL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ARQUIVO_OS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO_CENARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCONTRATO_NITEM_PDR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_USUARIO_DATA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1APONTAM_DATA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1OS_ESTIM.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKCENARIO_SERVICO_HORAS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1CENARIO_MOD_CONTR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TIPO_APONTAM.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTAREFA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1NOTA_FISCAL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK2USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1OS_NEGOCIACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE3CARTA_ACORDO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1NOTIFICA_FILA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__CARGO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKSIST_EXT_PARAMETRO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2ITEM_CRONO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2APONTAM_DATA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1PADRAO_PLANILHA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMI_PI_DESCARTE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCENARIO_EMPRESA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2MI_METAS_TV.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOPORTUNIDADE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE4TAREFA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKADIANT_REALIZ.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TIPO_DOCUMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKSALARIO_CARGO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1COMENTARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO_EMPRESA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCTX_ARQUIVO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKUSUARIO_PREF.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1HIST_ENDER.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__TAREFA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2XML_LOG.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO_DOCUMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_TIPO_PRODUTO_REF.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKUNIDADE_NEGOCIO_USU.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCONTRATO_ITEM.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1PESQUISA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2NOTIFICA_FILA_EMAIL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1CONTRATO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKORCAM_USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCARGO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKORCAMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1AREA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKABATIMENTO_CTR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1TASK_HIST.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCOMENTARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TIPO_INTEGRACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1HISTORICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKEMPRESA_SIST_EXT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2MILESTONE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKEMPRESA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPESSOA_SIST_EXT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1USUARIO_CARGO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE4TASK.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCENARIO_MOD_CONTR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TAB_FERIADO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_SNAP__MV_NEGOCIACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKEQUIPE_USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTASK.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTS_TRANSICAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TIPO_CONTRATO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKIMPOSTO_NOTA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\IDX04_MV_TAREFA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_INTEGRACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPAPEL_PAINEL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE3ITEM_NOTA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1JOB_HORAS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1MILESTONE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKNOTIFICA_PAPEL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPAPEL_PRIV.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKCONTRATO_HORAS_USU.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKNOTIFICA_DESLIGA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1CARTA_ACORDO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1BRIEFING.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTAREFA_TIPO_PRODUTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1EMAIL_CARTA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKNATUREZA_ITEM.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCONTRATO_USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ARQUIVO_JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ABATIMENTO_CTR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2NOTIFICA_FILA_USU.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE3TASK.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE3ITEM_FATUR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKHIST_SENHA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMILESTONE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1PAIS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\IDX02_MV_TAREFA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKSOLICIT_ADIANT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCONTRATO_FISICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1PREFERENCIA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOPORT_CONTRATO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCONDICAO_PAGTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKREL_APON_MENS_LIN.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMI_METAS_TV.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ARQUIVO_CONTRATO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKEMPRESA_PARAMETRO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1FATURAMENTO_CTR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKBRIEF_HIST.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKJOB_TIPO_PRODUTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_PRODUTO_VAR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKCENARIO_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKEVENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2JOB_RECEITA_CTR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPIFIC_MILESTONE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK2CONDICAO_PAGTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ITEM_SOBRA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_EVENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCEP.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPRODUTO_FISCAL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMOD_ITEM_CRONO_DIA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKBRIEF_ATRIBUTO_VALOR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKSALARIO_CARGO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1DUPLICATA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO_NF.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1TIPO_JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1MODAL_CONTRATACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_TAREFA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1ORCAMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMI_METAS_OOH.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ITEM_CARTA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1TIPO_APONTAM_JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1IMPOSTO_NOTA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1CENARIO_EMPRESA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKREGRA_COENDER.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1TAREFA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKCONTRATO_ITEM.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__ITEM_CRONO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1SALARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKSTATUS_AUX_JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKITEM_CRONO_DIA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1OS_LINK.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMETADADO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCONTRATO_HORAS.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1TAREFA_EVENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKJOB_RECEITA_CTR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCONTRATO_ELAB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKNATUREZA_OPER_FATUR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOBJETO_CRONO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2ITEM_FATUR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCOMUNICADO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_OS_TRANSICAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE4ORDEM_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMOD_ITEM_CRONO_PRE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPRIVILEGIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__DICIONARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1MI_METAS_TV.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1STATUS_AUX_JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTASK_HIST.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1SOLICIT_ADIANT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__JOB_USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCLASSE_PRODUTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKVOLUME.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__AREA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ITEM_HIST.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE6CARTA_ACORDO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ITEM_ABAT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__GRUPO_PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKFI_TIPO_IMPOSTO_PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1SOBRA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1FATURAMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTASK_COMENT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\IDX01_MV_ORDEM_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1TAREFA_AFAZER.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_REFACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1APONTAM_DATA_EV.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKDESP_REALIZ.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1LANCAMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKMOD_ITEM_CRONO_DEST.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKITEM_ABAT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK2OPORTUNIDADE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ARQUIVO_TASK.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2HISTORICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCONTRATO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2ITEM_ABAT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKJOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKAREA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\I_MLOG__ARQUIVO_PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ITEM_NOTA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ARQUIVO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_ESTIM.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE3APONTAM_HORA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\IDX05_MV_ORDEM_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPARCELA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1JOB_USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKPRECO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1ITEM_ADIANT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1CARTA_ACORDO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKPAINEL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1PARAMETRO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1DICION_EMP.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_USUARIO_REFACAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1OS_TRANSICAO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1JOB_PECA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTIPO_OBJETO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKEMAIL_CARTA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKTAREFA_EVENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKAPONTAM_HORA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAK1EQUIPE.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKNOTIFICA_CONFIG.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKAPONTAM_JOB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKDIA_SEMANA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKADNNET_OUT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1ADIANT_DESP.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKARQUIVO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE8PESSOA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1METADADO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1MI_METAS_PRINT.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\IDX05_MV_TAREFA.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1TASK.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\IDX06_MV_ORDEM_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKCOMENT_USUARIO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE1APONTAM_PROGR.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKABATIMENTO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKITEM_HIST.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\IDX04_MV_ORDEM_SERVICO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKEVENTO_MOTIVO.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XIE2ITEM.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XAKCONTRATO_ELAB.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKOS_AFAZER.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\XPKDICION_EMP_VAL.sql
@C:\projetos\jobone\sql\versionamento_codigo_fonte\Index\IDX01_MV_TAREFA.sql
