--------------------------------------------------------
--  Arquivo criado - segunda-feira-abril-14-2025   
--------------------------------------------------------
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\ABATIMENTO_CTR_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\ABATIMENTO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\ADIANT_DESP_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\APONTAM_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\APONTAM_PROGR_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\AREA_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\ARQUIVO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\BRIEFING_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\CAMPANHA_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\CARGA_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\CARGO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\CARTA_ACORDO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\CENARIO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\CEP_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\CNPJ_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\COMENTARIO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\COMUNICADO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\CONDICAO_PAGTO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\CONTRATO_ELAB_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\CONTRATO_FISICO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\CONTRATO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\CPF_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\CRONOGRAMA_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\DEPARTAMENTO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\DICIONARIO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\DICION_EMP_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\DOCUMENTO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\EMPRESA_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\EQUIPE_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\EVENTO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\FAIXA_APROV_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\FATURAMENTO_CTR_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\FATURAMENTO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\FERIADO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\FI_BANCO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\FLEX_PAPER_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\GRUPO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\HISTORICO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\IMPOSTO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\IT_ADNNET_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\IT_APOLO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\IT_CIGAM_ANT_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\IT_CIGAM_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\IT_CONTROLE_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\ITEM_DECUP_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\ITEM_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\IT_JOBONE_SELF_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\IT_PORTO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\IT_PROTHEUS_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\IT_SAP_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\JOB_HORAS_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\JOB_PECA_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\JOB_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\LIMPEZA_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\LINK_DIRETO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\METADADO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\MI_CARGA_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\MILESTONE_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\MOD_CRONO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\NATUREZA_ITEM_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\NATUREZA_OPER_FATUR_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\NOTA_FISCAL_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\OPORTUNIDADE_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\ORCAMENTO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\ORDEM_SERVICO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\PAINEL_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\PAPEL_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\PARCELA_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\PESQUISA_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\PESSOA_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\PRECO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\PRODUTO_CLIENTE_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\PRODUTO_FISCAL_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\QUADRO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\RAFAEL_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\REGRA_COENDER_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\RELATORIO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\RESULT_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\SALARIO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\SERVICO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\SETOR_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\SISTEMA_EXTERNO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\SISTEMA_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\SOAP_API_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\SOBRA_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\STATUS_AUX_JOB_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\STATUS_AUX_OPORT_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\TAREFA_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\TASK_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\TIPO_APONTAM_JOB_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\TIPO_APONTAM_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\TIPO_ARQUIVO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\TIPO_CONTRATO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\TIPO_DADO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\TIPO_DOCUMENTO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\TIPO_FINANCEIRO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\TIPO_JOB_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\TIPO_OS_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\TIPO_PRODUTO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\TIPO_TAREFA_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\UNIDADE_NEGOCIO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\USUARIO_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\UTIL_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\VOLUME_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\WEBSERVICE_PKG_1.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Spec\WEBSERVICEUTILS_PKG_1.sql
