--------------------------------------------------------
--  Arquivo criado - segunda-feira-abril-14-2025   
--------------------------------------------------------
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\ABATIMENTO_CTR_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\ABATIMENTO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\ADIANT_DESP_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\APONTAM_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\APONTAM_PROGR_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\AREA_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\ARQUIVO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\BRIEFING_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\CAMPANHA_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\CARGA_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\CARGO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\CARTA_ACORDO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\CENARIO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\CEP_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\CNPJ_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\COMENTARIO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\COMUNICADO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\CONDICAO_PAGTO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\CONTRATO_ELAB_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\CONTRATO_FISICO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\CONTRATO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\CPF_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\CRONOGRAMA_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\DEPARTAMENTO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\DICIONARIO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\DICION_EMP_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\DOCUMENTO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\EMPRESA_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\EQUIPE_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\EVENTO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\FAIXA_APROV_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\FATURAMENTO_CTR_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\FATURAMENTO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\FERIADO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\FI_BANCO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\FLEX_PAPER_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\GRUPO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\HISTORICO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\IMPOSTO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\IT_ADNNET_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\IT_APOLO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\IT_CIGAM_ANT_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\IT_CIGAM_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\IT_CONTROLE_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\ITEM_DECUP_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\ITEM_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\IT_JOBONE_SELF_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\IT_PORTO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\IT_PROTHEUS_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\IT_SAP_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\JOB_HORAS_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\JOB_PECA_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\JOB_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\LIMPEZA_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\LINK_DIRETO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\METADADO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\MI_CARGA_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\MILESTONE_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\MOD_CRONO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\NATUREZA_ITEM_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\NATUREZA_OPER_FATUR_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\NOTA_FISCAL_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\OPORTUNIDADE_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\ORCAMENTO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\ORDEM_SERVICO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\PAINEL_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\PAPEL_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\PARCELA_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\PESQUISA_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\PESSOA_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\PRECO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\PRODUTO_CLIENTE_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\PRODUTO_FISCAL_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\QUADRO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\RAFAEL_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\REGRA_COENDER_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\RELATORIO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\SALARIO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\SERVICO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\SETOR_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\SISTEMA_EXTERNO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\SISTEMA_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\SOAP_API_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\SOBRA_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\STATUS_AUX_JOB_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\STATUS_AUX_OPORT_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\TAREFA_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\TASK_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\TIPO_APONTAM_JOB_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\TIPO_APONTAM_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\TIPO_ARQUIVO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\TIPO_CONTRATO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\TIPO_DADO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\TIPO_DOCUMENTO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\TIPO_FINANCEIRO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\TIPO_JOB_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\TIPO_OS_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\TIPO_PRODUTO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\TIPO_TAREFA_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\UNIDADE_NEGOCIO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\USUARIO_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\UTIL_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\VOLUME_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\WEBSERVICE_PKG_2.sql
@C:\projetos\jobone\versionamento\Operacional\Packages\Body\WEBSERVICEUTILS_PKG_2.sql
