--------------------------------------------------------
--  Arquivo criado - terça-feira-abril-08-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Materialized View MV_NEGOCIACAO
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "JOBONE_V4"."MV_NEGOCIACAO" ("ORDEM_SERVICO_ID", "NUM_REFACAO", "QTDE")
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
   CACHE 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  REFRESH FAST ON COMMIT
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT ONX.ORDEM_SERVICO_ID,
       ONX.NUM_REFACAO,
       COUNT(1) AS QTDE
  FROM OS_NEGOCIACAO ONX
 GROUP
    BY ONX.ORDEM_SERVICO_ID,
       ONX.NUM_REFACAO;

  CREATE UNIQUE INDEX "JOBONE_V4"."I_SNAP$_MV_NEGOCIACAO" ON "JOBONE_V4"."MV_NEGOCIACAO" (SYS_OP_MAP_NONNULL("ORDEM_SERVICO_ID"), SYS_OP_MAP_NONNULL("NUM_REFACAO")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON MATERIALIZED VIEW "JOBONE_V4"."MV_NEGOCIACAO"  IS 'snapshot table for snapshot JOBONE_V4.MV_NEGOCIACAO';
  GRANT SELECT ON "JOBONE_V4"."MV_NEGOCIACAO" TO "WEB_JOBONE_ROLE";
